_commit: 0.1.7
_src_path: gh:mapp-metabolomics-unit/mapp-repo-copier-template
common_filename_pattern: '*mapp_01_*.mzML'
email: pierre-marie.allard@unifr.ch
gap_filling: false
git_repo_path: /Users/pma/git_repos/mapp-metabolomics-unit
github_username: mapp-metabolomics-unit
gnps_job_id: afe52ca0fbf24fbfb03e62ca14b14b9a
ionization_mode: positive
mapp_batch: mapp_batch_00153
mapp_batch_description: Pilot profiles of hemolymph - HILIC - QTOF - pos
mapp_project: mapp_project_00055
noise_level: 500000.0
repository_name: johnny-watanabe-group
target_variable: source_taxon
recorded_setup: true
recorded_repository_name: "johnny-watanabe-group"
recorded_author: "MAPP Metabolomics Unit"
recorder_email: "pierre-marie.allard@unifr.ch"
recorded_github_username: "mapp-metabolomics-unit"
recorded_mapp_project: "mapp_project_00055"
recorded_mapp_batch: "mapp_batch_00153"


