_commit: 0.0.90
_src_path: gh:mapp-metabolomics-unit/mapp-repo-copier-template
email: pierre-marie.allard@unifr.ch
git_repo_path: /Users/pma/git_repos/mapp-metabolomics-unit
github_username: mapp-metabolomics-unit
gnps_job_id: 9e16a42412034ce4b1a8ef6b6cf137cd
ionization_mode: positive
mapp_batch: mapp_batch_00114
mapp_batch_description: Untargeted metabolomics of Yeast cultures. Positive mode.
mapp_project: mapp_project_00051
repository_name: johnny-watanabe-group
target_variable: source_taxon
recorded_setup: true
recorded_repository_name: "johnny-watanabe-group"
recorded_author: "MAPP Metabolomics Unit"
recorder_email: "pierre-marie.allard@unifr.ch"
recorded_github_username: "mapp-metabolomics-unit"
recorded_mapp_project: "mapp_project_00051"
recorded_mapp_batch: "mapp_batch_00114"


